spring.application.name=meteoapp
server.servlet.context-path=/meteoapp

spring.datasource.url=jdbc:postgresql:meteodb
spring.datasource.username=meteo
spring.datasource.password=meteo
spring.jpa.hibernate.ddl-auto = validate

rest.connection.timeout = 17
rest.request.timeout = 23

jwt.sign = Ad9E2g7B8k4L0P60UTEM202508T2j5X4
jwt.pass = x17!kD2#qR9^Lm7$w,5@t13%hF3&jN6*

#
# LOG 
#
logging.level.cl.utem.meteo=DEBUG
