spring.application.name=meteo
server.servlet.context-path=/meteo

spring.datasource.url=jdbc:postgresql:meteodb
spring.datasource.username=meteo
spring.datasource.password=meteo
spring.jpa.hibernate.ddl-auto = validate

rest.connection.timeout = 17
rest.request.timeout = 23
