spring.application.name=meteoapp
server.servlet.context-path=/meteoapp

spring.datasource.url=jdbc:postgresql:meteodb
spring.datasource.username=meteo
spring.datasource.password=meteo
spring.jpa.hibernate.ddl-auto = validate

rest.connection.timeout = 17
rest.request.timeout = 23

#
# LOG 
#
logging.level.cl.utem.meteo=DEBUG
